const projectData = [
  {
    id: 1,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfPMkPPKXE4Sqb26cRmUj_i5L83qJjoopYr-B0b85kzTIvygPiKkr2GSMGB4GXu3sjhGs&usqp=CAU",
    alt: "voice1",
    title: "I Will Teach You To Be Rich",
    link: "View Project",
  },
  {
    id: 2,
    img: "https://us.123rf.com/450wm/bowie15/bowie151601/bowie15160100003/50717588-professional-photographer-in-the-street.jpg?ver=6",
    alt: "voice2",
    title: "Zero to one",
    link: "View Project",
  },
  {
    id: 3,
    img: "https://us.123rf.com/450wm/franz12/franz121807/franz12180701636/105140207-a-professional-travel-photographer-or-tourist-photographs-a-beautiful-urban-landscape-in-porto-in.jpg?ver=6",
    alt: "voice3",
    title: "Productize",
    link: "View Project",
  },
  {
    id: 4,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSA6lN7HWmMCjnme_X1OGaSCWvM9vGOM2a_M0v1JKlnkySlYhNFWjPILxs6IpG3VzHWWHw&usqp=CAU",
    alt: "voice4",
    title: "Strategy Os",
    link: "View Project",
  },
    {
      id: 5,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSA6lN7HWmMCjnme_X1OGaSCWvM9vGOM2a_M0v1JKlnkySlYhNFWjPILxs6IpG3VzHWWHw&usqp=CAU",
      alt: "voice5",
      title: "Of The Secrets Of The Qur'an",
      link: "??",
    },
    {
      id: 6,
      img: "https://m.media-amazon.com/images/I/41JFxtR5J1L._SY291_BO1,204,203,200_QL40_FMwebp_.jpg",
      alt: "voice6",
      title: "Why No One Is Buying Your Product",
      link: "??",    },
    {
      id: 7,
      img: "https://m.media-amazon.com/images/I/41zbk6Q0plL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg",
      alt: "voice7",
      title: "How to Win Friends and Influence People",
      link: "??",    },

    {
      id: 8,
      img: "https://m.media-amazon.com/images/I/41yf27Q-0zL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg",
      alt: "voice8",
      title: "The Laws of Human Nature",
      link: "??",    },

  {
    id: 9,
    img: "https://m.media-amazon.com/images/I/41j2J+8BcZL._SY344_BO1,204,203,200_.jpg",
    alt: "voice9",
    title: "The Law Of War",
    link: "??",
  },

  {
    id: 10,
    img: "https://m.media-amazon.com/images/I/41GCAmfAmNL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg",
    alt: "voice10",
    title: "Psychology of Human Behavior",
    link: "??",
  },
  {
    id: 11,
    img: "https://m.media-amazon.com/images/I/41T-XHe8-EL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg",
    alt: "voice11",
    title: "The body keeps the score",
    link: "??",
  },
  {
    id: 12,
    img: "https://m.media-amazon.com/images/I/41q91ld1d6L._SY291_BO1,204,203,200_QL40_FMwebp_.jpg",
    alt: "voice12",
    title: "It Didn't Start With You",
    link: "??",
  },

  {
    id: 13,
    img: "https://scoopempire.com/wp-content/uploads/2016/05/arab-books-pic-9.jpg",
    alt: "voice13",
    title: "Bamboo Stalk",
    link: "??",
  },
  {
    id: 14,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREhPUfwSwTGnuuxI-sKf5w9_uYwA--hQmnqlONjDqU0Y_4wuW514drFjMog9LYnHTqhsg&usqp=CAU",
    alt: "voice14",
    title: "The Nightingale's Prayer",
    link: "??",
  },
  {
    id: 15,
    img: "https://m.media-amazon.com/images/I/51vf0I-ZRpL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg",
    alt: "voice15",
    title: "Using Behavioral Science in Marketing",
   link: "??",
  },
  // {
  //   id: 16,
  //   src: "https://m.media-amazon.com/images/I/51Hfv2MfNGL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg",
  //   alt: "Cat 1",
  //   title: "Rich Dad poor Dad",
  //   author: "Rober T. Kiyosaki",
  //   numberOfbook: 124,
  //   rating: 2.5,
  //   bookmarked: false,
  // },

  // {
  //   id: 17,
  //   src: "https://m.media-amazon.com/images/I/51B7kuFwQFL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg",
  //   alt: "Cat 6",
  //   title: "Atomic Habits",
  //   author: "James Clear",
  //   numberOfbook: 121,
  //   rating: 4.5,
  //   bookmarked: false,
  // },
  // {
  //   id: 18,
  //   src: "https://m.media-amazon.com/images/I/41boGl0Y-QL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg",
  //   alt: "Cat 1",
  //   title: "Surrounded by idiots",
  //   author: "Thomas erikson",
  //   numberOfbook: 120,
  //   rating: 3.1,
  //   bookmarked: false,
  // },
  // {
  //   id: 19,
  //   src: "https://m.media-amazon.com/images/I/41vXYYwWlvL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg",
  //   alt: "Cat 1",
  //   title: "Python Basics",
  //   author: " David Amos.",
  //   numberOfbook: 109,
  //   rating: 1.5,
  //   bookmarked: false,
  // },

  // {
  //   id: 20,
  //   src: "https://books-library.net/files/s-books-library.net-05222136Ua5R1.jpg",
  //   alt: "Cat 1",
  //   title: "The Era Of The Monkeys",
  //   author: "D. Mustafa Mahmoud",
  //   numberOfbook: 104,
  //   rating: 4.5,
  //   bookmarked: false,
  // },
  // {
  //   id: 21,
  //   src: "https://orion-uploads.openroadmedia.com/sm_f7e651-tolkien-lordoftherings.jpg",
  //   alt: "Cat 1",
  //   title: "The Lord of the rings",
  //   author: "J.r.r Tolkien",
  //   numberOfbook: 94,
  //   rating: 2.5,
  //   bookmarked: false,
  // },

  // {
  //   id: 22,
  //   src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbQ83Wnf_zrvaLmu5aJdN-sC5sH93fZsbW2A&usqp=CAU",
  //   alt: "Book",
  //   title: "Little women",
  //   author: "Louisa May Alcott",
  //   numberOfbook: 82,
  //   rating: 4.9,
  //   bookmarked: false,
  // },

  // {
  //   id: 23,
  //   src: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Mark_Twain_by_AF_Bradley.jpg/640px-Mark_Twain_by_AF_Bradley.jpg",
  //   alt: "Book",
  //   title: "Literary Theory and Criticism",
  //   author: "Mark Twain",
  //   numberOfbook: 81,
  //   rating: 4.1,
  //   bookmarked: false,
  // },

  // {
  //   id: 24,
  //   src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZ6e6bgALIDppYUcspSXLiU8yzX_8kn7SDLA&usqp=CAU",
  //   alt: "Book",
  //   title: "Girl made of Gold",
  //   author: "Saurabh Sharma",
  //   numberOfbook: 71,
  //   rating: 4.8,
  //   bookmarked: false,
  // },
];

export default projectData;
